version: '3.7'
services:
  s3:
   image: quay.io/minio/minio:RELEASE.2022-09-01T23-53-36Z.fips
   container_name: minio
   volumes:
     - ~/volumes/s3/minio/data:/data
   environment:
     - MINIO_ROOT_USER=minio
     - MINIO_ROOT_PASSWORD=miniostorage
   command: server /data --console-address ":9001"
   ports:
    - 9000:9000
    - 9001:9001
   healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3


#  --user $(id -u):$(id -g)
