version: '3'
services:
  postgresql:
    image: postgres:10.13-alpine
    container_name: postgresql
    volumes:
      - ~/volumes/spring/demo/postgresql/data/:/var/lib/postgresql/data/
    environment:
#      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=keycloak
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
