version: '3.8'
services:
  gateway-app:
    container_name: gateway-react
    image: ucm/gateway-react:0.0.1-SNAPSHOT
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8000
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${application.registry-config.password}@192.168.1.10:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${application.registry-config.password}@192.168.1.10:8761/config
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI=http://192.168.1.10:9080/realms/jhipster
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_ID=web_app
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_SECRET=web_app
    ports:
      - 8000:8000
    depends_on:
      - keycloak
      - jhipster-registry
      - elasticsearch
    networks:
      - backend_spring

  directory-app:
    container_name: directory
    image: ucm/directory:0.0.1-snapshot
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${application.registry-config.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${application.registry-config.password}@jhipster-registry:8761/config
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/directory
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI=http://192.168.1.10:9080/realms/jhipster
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_ID=internal
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_SECRET=internal
      - SPRING_ELASTICSEARCH_REST_URIS=http://192.168.1.10:9200
    ports:
      - 127.0.0.1:8081:8081
    depends_on:
      - keycloak
      - jhipster-registry
      - elasticsearch
      - s3
      - postgresql
    networks:
      - backend_spring
